# Generated by CodeSpeak from spec file: packages/markitdown/src/markitdown/converters/eml_converter.cs.md
# Modifying this file manually is DISCOURAGED.
# CodeSpeak will try to preserve manual changes, but it's not guaranteed.

import email
import email.header
import email.message
from typing import Any, BinaryIO, List, Optional, Tuple

from .._base_converter import DocumentConverter, DocumentConverterResult
from .._stream_info import StreamInfo
from ._html_converter import HtmlConverter

ACCEPTED_MIME_TYPE_PREFIXES = [
    "message/rfc822",
]

ACCEPTED_FILE_EXTENSIONS = [".eml"]


def _decode_header(value: Optional[str]) -> str:
    """Decode RFC 2047 encoded header values (e.g. =?UTF-8?B?...?=)."""
    if value is None:
        return ""
    decoded_parts: List[str] = []
    for part, charset in email.header.decode_header(value):
        if isinstance(part, bytes):
            decoded_parts.append(part.decode(charset or "utf-8", errors="replace"))
        else:
            decoded_parts.append(part)
    return "".join(decoded_parts)


def _human_readable_size(size_bytes: int) -> str:
    """Convert a byte count to a human-readable string."""
    if size_bytes < 1024:
        return f"{size_bytes} bytes"
    elif size_bytes < 1024 * 1024:
        return f"{size_bytes / 1024:.1f} KB"
    elif size_bytes < 1024 * 1024 * 1024:
        return f"{size_bytes / (1024 * 1024):.1f} MB"
    else:
        return f"{size_bytes / (1024 * 1024 * 1024):.1f} GB"


def _get_body_and_attachments(
    msg: email.message.Message,
) -> Tuple[
    Optional[str],
    Optional[str],
    List[Tuple[str, str, int]],
    List[email.message.Message],
]:
    """Walk a message, extracting text/plain body, text/html body, attachment metadata,
    and nested message/rfc822 parts.

    Returns:
        (plain_text_body, html_body, attachments, nested_messages)
        where attachments is a list of (filename, content_type, size_bytes) tuples,
        and nested_messages is a list of email.message.Message objects.
    """
    plain_body: Optional[str] = None
    html_body: Optional[str] = None
    attachments: List[Tuple[str, str, int]] = []
    nested_messages: List[email.message.Message] = []

    for part in msg.walk():
        content_type = part.get_content_type()
        content_disposition = str(part.get("Content-Disposition", ""))

        # Handle nested message/rfc822 parts (but skip the top-level message itself)
        if content_type == "message/rfc822" and part is not msg:
            # The payload of a message/rfc822 part is a list containing the nested message
            payload = part.get_payload()
            if isinstance(payload, list):
                for nested_msg in payload:
                    if isinstance(nested_msg, email.message.Message):
                        nested_messages.append(nested_msg)
            elif isinstance(payload, email.message.Message):
                nested_messages.append(payload)
            continue

        # Skip multipart containers themselves
        if part.get_content_maintype() == "multipart":
            continue

        # Determine if this part is an attachment
        if "attachment" in content_disposition:
            filename = part.get_filename() or "unnamed"
            filename = _decode_header(filename)
            # Get the raw payload size without decoding content
            payload = part.get_payload(decode=True)
            size = len(payload) if payload else 0
            attachments.append((filename, content_type, size))
            continue

        # Collect body parts
        if content_type == "text/plain" and plain_body is None:
            payload = part.get_payload(decode=True)
            if payload:
                charset = part.get_content_charset() or "utf-8"
                plain_body = payload.decode(charset, errors="replace")
        elif content_type == "text/html" and html_body is None:
            payload = part.get_payload(decode=True)
            if payload:
                charset = part.get_content_charset() or "utf-8"
                html_body = payload.decode(charset, errors="replace")

    return plain_body, html_body, attachments, nested_messages


def _format_message(
    msg: email.message.Message,
    html_converter: HtmlConverter,
    **kwargs: Any,
) -> str:
    """Format an email message as Markdown.

    Args:
        msg: The email message to format.
        html_converter: An HtmlConverter instance for converting HTML bodies.
        **kwargs: Additional keyword arguments passed to the HTML converter.

    Returns:
        The formatted Markdown string.
    """
    lines: List[str] = []

    # Headers section
    header_fields = ["From", "To", "Cc", "Subject", "Date"]
    for field in header_fields:
        value = _decode_header(msg.get(field))
        if value:
            lines.append(f"**{field}:** {value}")

    lines.append("")  # blank line after headers

    # Body
    plain_body, html_body, attachments, nested_messages = _get_body_and_attachments(msg)

    if plain_body:
        lines.append(plain_body.strip())
    elif html_body:
        result = html_converter.convert_string(html_body, **kwargs)
        lines.append(result.markdown.strip())

    # Nested messages (message/rfc822 parts) - formatted as quoted blocks
    for nested_msg in nested_messages:
        lines.append("")
        lines.append("**Nested Message:**")
        lines.append("")
        nested_text = _format_message(nested_msg, html_converter, **kwargs)
        for line in nested_text.split("\n"):
            lines.append(f"> {line}")

    # Attachments section
    if attachments:
        lines.append("")
        lines.append("**Attachments:**")
        lines.append("")
        for filename, content_type, size in attachments:
            readable_size = _human_readable_size(size)
            lines.append(f"- {filename} ({content_type}, {readable_size})")

    return "\n".join(lines)


class EmlConverter(DocumentConverter):
    """Converts RFC 5322 email files (.eml) to Markdown.

    Uses Python's built-in email module to parse .eml files and extract:
    - Email headers (From, To, Cc, Subject, Date)
    - Email body (prefers text/plain over text/html)
    - Attachment metadata (filename, MIME type, human-readable size)
    - Nested message/rfc822 parts (formatted as quoted blocks)
    """

    def __init__(self) -> None:
        super().__init__()
        self._html_converter = HtmlConverter()

    def accepts(
        self,
        file_stream: BinaryIO,
        stream_info: StreamInfo,
        **kwargs: Any,
    ) -> bool:
        mimetype = (stream_info.mimetype or "").lower()
        extension = (stream_info.extension or "").lower()

        if extension in ACCEPTED_FILE_EXTENSIONS:
            return True

        for prefix in ACCEPTED_MIME_TYPE_PREFIXES:
            if mimetype.startswith(prefix):
                return True

        return False

    def convert(
        self,
        file_stream: BinaryIO,
        stream_info: StreamInfo,
        **kwargs: Any,
    ) -> DocumentConverterResult:
        raw_bytes = file_stream.read()
        msg = email.message_from_bytes(raw_bytes)

        subject = _decode_header(msg.get("Subject"))

        markdown = _format_message(msg, self._html_converter, **kwargs)

        return DocumentConverterResult(
            markdown=markdown.strip(),
            title=subject if subject else None,
        )
