# Generated by CodeSpeak from spec file: packages/markitdown/src/markitdown/converters/_outlook_msg_converter.cs.md
# Modifying this file manually is DISCOURAGED.
# CodeSpeak will try to preserve manual changes, but it's not guaranteed.

import sys
from typing import Any, Union, BinaryIO, List, Dict
from .._stream_info import StreamInfo
from .._base_converter import DocumentConverter, DocumentConverterResult
from .._exceptions import MissingDependencyException, MISSING_DEPENDENCY_MESSAGE

# Try loading optional (but in this case, required) dependencies
# Save reporting of any exceptions for later
_dependency_exc_info = None
olefile = None
try:
    import olefile  # type: ignore[no-redef]
except ImportError:
    # Preserve the error and stack trace for later
    _dependency_exc_info = sys.exc_info()

ACCEPTED_MIME_TYPE_PREFIXES = [
    "application/vnd.ms-outlook",
]

ACCEPTED_FILE_EXTENSIONS = [".msg"]


class OutlookMsgConverter(DocumentConverter):
    """Converts Outlook .msg files to markdown by extracting email metadata and content.

    Uses the olefile package to parse the .msg file structure and extract:
    - Email headers (From, To, Subject)
    - Email body content
    """

    def accepts(
        self,
        file_stream: BinaryIO,
        stream_info: StreamInfo,
        **kwargs: Any,  # Options to pass to the converter
    ) -> bool:
        mimetype = (stream_info.mimetype or "").lower()
        extension = (stream_info.extension or "").lower()

        # Check the extension and mimetype
        if extension in ACCEPTED_FILE_EXTENSIONS:
            return True

        for prefix in ACCEPTED_MIME_TYPE_PREFIXES:
            if mimetype.startswith(prefix):
                return True

        # Brute force, check if we have an OLE file
        cur_pos = file_stream.tell()
        try:
            if olefile and not olefile.isOleFile(file_stream):
                return False
        finally:
            file_stream.seek(cur_pos)

        # Brue force, check if it's an Outlook file
        try:
            if olefile is not None:
                msg = olefile.OleFileIO(file_stream)
                toc = "\n".join([str(stream) for stream in msg.listdir()])
                return (
                    "__properties_version1.0" in toc
                    and "__recip_version1.0_#00000000" in toc
                )
        except Exception as e:
            pass
        finally:
            file_stream.seek(cur_pos)

        return False

    def convert(
        self,
        file_stream: BinaryIO,
        stream_info: StreamInfo,
        **kwargs: Any,  # Options to pass to the converter
    ) -> DocumentConverterResult:
        # Check: the dependencies
        if _dependency_exc_info is not None:
            raise MissingDependencyException(
                MISSING_DEPENDENCY_MESSAGE.format(
                    converter=type(self).__name__,
                    extension=".msg",
                    feature="outlook",
                )
            ) from _dependency_exc_info[
                1
            ].with_traceback(  # type: ignore[union-attr]
                _dependency_exc_info[2]
            )

        assert (
            olefile is not None
        )  # If we made it this far, olefile should be available
        msg = olefile.OleFileIO(file_stream)

        # Extract email metadata
        md_content = "# Email Message\n\n"

        # Get headers
        headers = {
            "From": self._get_stream_data(msg, "__substg1.0_0C1F001F"),
            "To": self._get_stream_data(msg, "__substg1.0_0E04001F"),
            "Cc": self._get_stream_data(msg, "__substg1.0_0E03001F"),
            "Bcc": self._get_stream_data(msg, "__substg1.0_0E02001F"),
            "Subject": self._get_stream_data(msg, "__substg1.0_0037001F"),
            "Date": self._get_stream_data(msg, "__substg1.0_0039001F"),
        }

        # Add headers to markdown
        for key, value in headers.items():
            if value:
                md_content += f"**{key}:** {value}\n"

        md_content += "\n## Content\n\n"

        # Get email body
        body = self._get_stream_data(msg, "__substg1.0_1000001F")
        if body:
            md_content += body

        # Get attachments
        attachments = self._get_attachments(msg)
        if attachments:
            md_content += "\n\n## Attachments\n\n"
            for attachment in attachments:
                md_content += f"- {attachment['filename']} ({attachment['size']})\n"

        msg.close()

        return DocumentConverterResult(
            markdown=md_content.strip(),
            title=headers.get("Subject"),
        )

    def _get_stream_data(self, msg: Any, stream_path: str) -> Union[str, None]:
        """Helper to safely extract and decode stream data from the MSG file."""
        assert olefile is not None
        assert isinstance(
            msg, olefile.OleFileIO
        )  # Ensure msg is of the correct type (type hinting is not possible with the optional olefile package)

        try:
            if msg.exists(stream_path):
                data = msg.openstream(stream_path).read()
                # Try UTF-16 first (common for .msg files)
                try:
                    return data.decode("utf-16-le").strip().rstrip('\x00')
                except UnicodeDecodeError:
                    # Fall back to UTF-8
                    try:
                        return data.decode("utf-8").strip().rstrip('\x00')
                    except UnicodeDecodeError:
                        # Last resort - ignore errors
                        return data.decode("utf-8", errors="ignore").strip().rstrip('\x00')
        except Exception:
            pass
        return None

    def _get_attachments(self, msg: Any) -> List[Dict[str, str]]:
        """Extract attachment metadata from the MSG file."""
        assert olefile is not None
        assert isinstance(msg, olefile.OleFileIO)
        
        attachments = []
        attachment_paths = set()
        
        try:
            # Find all attachment sub-storages
            toc = msg.listdir()
            for entry in toc:
                # entry is a list like ['__attach_version1.0_#00000000', '__substg1.0_3707001F']
                if len(entry) >= 1 and entry[0].startswith("__attach_version1.0_#"):
                    # This is an attachment directory
                    attachment_paths.add(entry[0])
            
            for attachment_path in sorted(attachment_paths):
                attachment_info = self._extract_attachment_info(msg, attachment_path)
                if attachment_info:
                    attachments.append(attachment_info)
                    
        except Exception:
            pass
        
        return attachments

    def _extract_attachment_info(self, msg: Any, attachment_path: str) -> Union[Dict[str, str], None]:
        """Extract filename and size for a specific attachment."""
        try:
            # Try to get display name first, fall back to filename
            filename = self._get_stream_data(msg, f"{attachment_path}/__substg1.0_3707001F")
            if not filename:
                filename = self._get_stream_data(msg, f"{attachment_path}/__substg1.0_3704001F")
            
            if not filename:
                return None
                
            # Get attachment size from data stream
            data_stream_path = f"{attachment_path}/__substg1.0_37010102"
            size = 0
            try:
                if msg.exists(data_stream_path):
                    data = msg.openstream(data_stream_path).read()
                    size = len(data)
            except Exception:
                pass
            
            return {
                "filename": filename,
                "size": self._format_file_size(size)
            }
        except Exception:
            return None

    def _format_file_size(self, size_bytes: int) -> str:
        """Format file size in human-readable format."""
        if size_bytes == 0:
            return "0 bytes"
        
        units = ['bytes', 'KB', 'MB', 'GB', 'TB']
        size = float(size_bytes)
        unit_index = 0
        
        while size >= 1024 and unit_index < len(units) - 1:
            size /= 1024
            unit_index += 1
        
        if unit_index == 0:
            return f"{int(size)} {units[unit_index]}"
        else:
            return f"{size:.1f} {units[unit_index]}"
